import type { Metadata } from "next";
import {Inter_Tight} from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tightInter = Inter_Tight({
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={tightInter.className}>
      <body>
        <header></header>
        {children}
      </body>
    </html>
  );
}
